// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	go_postgis "github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5/pgtype"
)

type Measurement struct {
	Time             pgtype.Timestamp
	WaterMeterDevEUI string
	WaterSupplyId    pgtype.Int4
	Measurement      int32
	Delta            int32
}

type RtMeasurement struct {
	Time             pgtype.Timestamp
	WaterMeterDevEUI string
	WaterSupplyId    pgtype.Int4
	Measurement      int32
	Alarms           string
}

type WaterMeter struct {
	ID                int32
	DevEUI            string
	SerialNumber      string
	BrandName         string
	LtPerPulse        int32
	CurrentReading    pgtype.Int4
	IsActive          bool
	AlarmStatus       bool
	NoFlow            bool
	DeviceHandshake   pgtype.Int4
	DeviceLogging     pgtype.Int4
	ServerHandshake   pgtype.Int4
	ServerLogging     pgtype.Int4
	InactivityTimeout int32
	LastSeen          pgtype.Timestamp
	Rssi              pgtype.Int4
	Snr               pgtype.Float8
	SpreadingFactor   pgtype.Int4
	GatewayId         pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type WaterSupply struct {
	ID               int32
	SupplyNumber     string
	Geometry         go_postgis.Point
	WaterMeterDevEUI pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	IsActive         pgtype.Bool
}
